
import Navbar from './components/Navbar'
import './styles.css'
export const metadata = {
  title: 'Next.js',
  description: 'Generated by Next.js',
}

export default function RootLayout({
  children,
}: {
  children: React.ReactNode
}) {
  return (
    <html lang="en">

      <body className="bg-slate-300">
        <header>
          <Navbar />
        </header>
        {children}
      </body>
    </html>
  )
}
